# Generated by Django 2.2.6 on 2021-02-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgtext', '0002_imgfile_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgfile',
            name='imgs',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
