# Generated by Django 2.2.6 on 2021-02-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgtext', '0003_auto_20210222_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgfile',
            name='imgs',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
