# Generated by Django 2.2.6 on 2021-02-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgtext', '0005_auto_20210222_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgfile',
            name='text',
        ),
    ]
